import { execa } from 'execa';
import { existsSync } from 'node:fs';
import { copyFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { resolveLoader } from './download.js';
import { info, success, die } from './log.js';

export async function wrapBinary(
  upstreamBin: string,
  runtimeOut: string,
  loaderDir: string,
): Promise<void> {
  const loaderPath = await resolveLoader(loaderDir);

  info('wrapping upstream binary for Termux/Android');
  await execa('python3', ['build.py', upstreamBin, '--wrapper', './wrapper'], {
    cwd: loaderPath,
  });

  // build.py outputs opencode-termux alongside the input binary
  const binDir = resolve(upstreamBin, '..');
  const wrapped = resolve(binDir, 'opencode-termux');

  if (!existsSync(wrapped)) die('wrapped runtime not generated by bun-termux-loader');
  await copyFile(wrapped, runtimeOut);
  await execa('chmod', ['755', runtimeOut]);

  info('wrapped runtime verification');
  const { stdout: fileInfo } = await execa('file', [runtimeOut]);
  info(fileInfo);

  const { stdout: verOut } = await execa(runtimeOut, ['--version']);
  success(`runtime version: ${verOut.trim()}`);
}
